/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IVotesTokenInterface extends Interface {
    getFunction(nameOrSignature: "getPastTotalSupply" | "getPastVotes"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getPastTotalSupply', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPastVotes', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getPastTotalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPastVotes', data: BytesLike): Result;
  }

  

  export interface IVotesToken extends BaseContract {
    
    connect(runner?: ContractRunner | null): IVotesToken;
    waitForDeployment(): Promise<this>;

    interface: IVotesTokenInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getPastTotalSupply: TypedContractMethod<
      [timepoint: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getPastVotes: TypedContractMethod<
      [account: AddressLike, timepoint: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getPastTotalSupply'): TypedContractMethod<
      [timepoint: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPastVotes'): TypedContractMethod<
      [account: AddressLike, timepoint: BigNumberish, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }