/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AegisProjectInterface extends Interface {
    getFunction(nameOrSignature: "VOTING_PERIOD" | "backers" | "cancelProject" | "claimRefund" | "contribute" | "contributions" | "creator" | "description" | "finalizeMilestone" | "fundingDeadline" | "fundingGoal" | "getBackers" | "getContractBalance" | "getMilestoneCount" | "getMilestones" | "getProjectSummary" | "hasVoted" | "milestones" | "name" | "state" | "submitMilestoneReport" | "totalFunded" | "totalReleased" | "voteOnMilestone"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Contributed" | "FundsReleased" | "MilestoneApproved" | "MilestoneRejected" | "MilestoneSubmitted" | "ProjectActivated" | "ProjectCancelled" | "ProjectCompleted" | "RefundClaimed" | "VoteCast"): EventFragment;

    encodeFunctionData(functionFragment: 'VOTING_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'backers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelProject', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimRefund', values?: undefined): string;
encodeFunctionData(functionFragment: 'contribute', values?: undefined): string;
encodeFunctionData(functionFragment: 'contributions', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'creator', values?: undefined): string;
encodeFunctionData(functionFragment: 'description', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalizeMilestone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundingDeadline', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundingGoal', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBackers', values?: undefined): string;
encodeFunctionData(functionFragment: 'getContractBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMilestoneCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMilestones', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProjectSummary', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'milestones', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'state', values?: undefined): string;
encodeFunctionData(functionFragment: 'submitMilestoneReport', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'totalFunded', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalReleased', values?: undefined): string;
encodeFunctionData(functionFragment: 'voteOnMilestone', values: [BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'VOTING_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'backers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'description', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundingDeadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundingGoal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBackers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContractBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestoneCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProjectSummary', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'milestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'state', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitMilestoneReport', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalFunded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalReleased', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteOnMilestone', data: BytesLike): Result;
  }

  
    export namespace ContributedEvent {
      export type InputTuple = [backer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [backer: string, amount: bigint];
      export interface OutputObject {backer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsReleasedEvent {
      export type InputTuple = [milestoneId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [milestoneId: bigint, amount: bigint];
      export interface OutputObject {milestoneId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [milestoneId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [milestoneId: bigint, amount: bigint];
      export interface OutputObject {milestoneId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneRejectedEvent {
      export type InputTuple = [milestoneId: BigNumberish];
      export type OutputTuple = [milestoneId: bigint];
      export interface OutputObject {milestoneId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneSubmittedEvent {
      export type InputTuple = [milestoneId: BigNumberish, reportURI: string];
      export type OutputTuple = [milestoneId: bigint, reportURI: string];
      export interface OutputObject {milestoneId: bigint, reportURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectActivatedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCancelledEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCompletedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundClaimedEvent {
      export type InputTuple = [backer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [backer: string, amount: bigint];
      export interface OutputObject {backer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [milestoneId: BigNumberish, voter: AddressLike, approve: boolean, weight: BigNumberish];
      export type OutputTuple = [milestoneId: bigint, voter: string, approve: boolean, weight: bigint];
      export interface OutputObject {milestoneId: bigint, voter: string, approve: boolean, weight: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AegisProject extends BaseContract {
    
    connect(runner?: ContractRunner | null): AegisProject;
    waitForDeployment(): Promise<this>;

    interface: AegisProjectInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    VOTING_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    backers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    cancelProject: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimRefund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    contribute: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    contributions: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    creator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    description: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    finalizeMilestone: TypedContractMethod<
      [_milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundingDeadline: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fundingGoal: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getBackers: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getContractBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getMilestoneCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getMilestones: TypedContractMethod<
      [],
      [[string[], bigint[], bigint[], bigint[], string[], bigint[], bigint[], bigint[]] & {descriptions: string[], amounts: bigint[], deadlines: bigint[], statuses: bigint[], reportURIs: string[], yesVotesArr: bigint[], noVotesArr: bigint[], votingDeadlines: bigint[] }],
      'view'
    >
    

    
    getProjectSummary: TypedContractMethod<
      [],
      [[string, string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {_creator: string, _name: string, _description: string, _fundingGoal: bigint, _fundingDeadline: bigint, _totalFunded: bigint, _state: bigint, _milestoneCount: bigint, _totalReleased: bigint }],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    milestones: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, string, bigint, bigint, bigint] & {description: string, amount: bigint, deadline: bigint, status: bigint, reportURI: string, yesVotes: bigint, noVotes: bigint, votingDeadline: bigint }],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    state: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    submitMilestoneReport: TypedContractMethod<
      [_milestoneId: BigNumberish, _reportURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    totalFunded: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalReleased: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    voteOnMilestone: TypedContractMethod<
      [_milestoneId: BigNumberish, _approve: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'VOTING_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'backers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelProject'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimRefund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contribute'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'contributions'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'creator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'description'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'finalizeMilestone'): TypedContractMethod<
      [_milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundingDeadline'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fundingGoal'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getBackers'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getContractBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMilestoneCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMilestones'): TypedContractMethod<
      [],
      [[string[], bigint[], bigint[], bigint[], string[], bigint[], bigint[], bigint[]] & {descriptions: string[], amounts: bigint[], deadlines: bigint[], statuses: bigint[], reportURIs: string[], yesVotesArr: bigint[], noVotesArr: bigint[], votingDeadlines: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getProjectSummary'): TypedContractMethod<
      [],
      [[string, string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {_creator: string, _name: string, _description: string, _fundingGoal: bigint, _fundingDeadline: bigint, _totalFunded: bigint, _state: bigint, _milestoneCount: bigint, _totalReleased: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'milestones'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, string, bigint, bigint, bigint] & {description: string, amount: bigint, deadline: bigint, status: bigint, reportURI: string, yesVotes: bigint, noVotes: bigint, votingDeadline: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'state'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submitMilestoneReport'): TypedContractMethod<
      [_milestoneId: BigNumberish, _reportURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalFunded'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalReleased'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'voteOnMilestone'): TypedContractMethod<
      [_milestoneId: BigNumberish, _approve: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Contributed'): TypedContractEvent<ContributedEvent.InputTuple, ContributedEvent.OutputTuple, ContributedEvent.OutputObject>;
getEvent(key: 'FundsReleased'): TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'MilestoneRejected'): TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
getEvent(key: 'MilestoneSubmitted'): TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
getEvent(key: 'ProjectActivated'): TypedContractEvent<ProjectActivatedEvent.InputTuple, ProjectActivatedEvent.OutputTuple, ProjectActivatedEvent.OutputObject>;
getEvent(key: 'ProjectCancelled'): TypedContractEvent<ProjectCancelledEvent.InputTuple, ProjectCancelledEvent.OutputTuple, ProjectCancelledEvent.OutputObject>;
getEvent(key: 'ProjectCompleted'): TypedContractEvent<ProjectCompletedEvent.InputTuple, ProjectCompletedEvent.OutputTuple, ProjectCompletedEvent.OutputObject>;
getEvent(key: 'RefundClaimed'): TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;

    filters: {
      
      'Contributed(address,uint256)': TypedContractEvent<ContributedEvent.InputTuple, ContributedEvent.OutputTuple, ContributedEvent.OutputObject>;
      Contributed: TypedContractEvent<ContributedEvent.InputTuple, ContributedEvent.OutputTuple, ContributedEvent.OutputObject>;
    

      'FundsReleased(uint256,uint256)': TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
      FundsReleased: TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
    

      'MilestoneApproved(uint256,uint256)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'MilestoneRejected(uint256)': TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
      MilestoneRejected: TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
    

      'MilestoneSubmitted(uint256,string)': TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
      MilestoneSubmitted: TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
    

      'ProjectActivated()': TypedContractEvent<ProjectActivatedEvent.InputTuple, ProjectActivatedEvent.OutputTuple, ProjectActivatedEvent.OutputObject>;
      ProjectActivated: TypedContractEvent<ProjectActivatedEvent.InputTuple, ProjectActivatedEvent.OutputTuple, ProjectActivatedEvent.OutputObject>;
    

      'ProjectCancelled()': TypedContractEvent<ProjectCancelledEvent.InputTuple, ProjectCancelledEvent.OutputTuple, ProjectCancelledEvent.OutputObject>;
      ProjectCancelled: TypedContractEvent<ProjectCancelledEvent.InputTuple, ProjectCancelledEvent.OutputTuple, ProjectCancelledEvent.OutputObject>;
    

      'ProjectCompleted()': TypedContractEvent<ProjectCompletedEvent.InputTuple, ProjectCompletedEvent.OutputTuple, ProjectCompletedEvent.OutputObject>;
      ProjectCompleted: TypedContractEvent<ProjectCompletedEvent.InputTuple, ProjectCompletedEvent.OutputTuple, ProjectCompletedEvent.OutputObject>;
    

      'RefundClaimed(address,uint256)': TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
      RefundClaimed: TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
    

      'VoteCast(uint256,address,bool,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    
    };
  }