/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AegisCrowdfundFactory {
      
    export type CreateProjectParamsStruct = {name: string, description: string, fundingGoal: BigNumberish, fundingDeadline: BigNumberish, mDescriptions: string[], mAmounts: BigNumberish[], mDeadlines: BigNumberish[]}

    export type CreateProjectParamsStructOutput = [name: string, description: string, fundingGoal: bigint, fundingDeadline: bigint, mDescriptions: string[], mAmounts: bigint[], mDeadlines: bigint[]] & {name: string, description: string, fundingGoal: bigint, fundingDeadline: bigint, mDescriptions: string[], mAmounts: bigint[], mDeadlines: bigint[] }
  
    }

  export interface AegisCrowdfundFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createProject" | "creatorProjects" | "getProjectCount" | "getProjects" | "getProjectsByCreator" | "governanceToken" | "projects"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProjectCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createProject', values: [AegisCrowdfundFactory.CreateProjectParamsStruct]): string;
encodeFunctionData(functionFragment: 'creatorProjects', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProjectCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProjects', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProjectsByCreator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'governanceToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'projects', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creatorProjects', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProjectCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProjects', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProjectsByCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'governanceToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projects', data: BytesLike): Result;
  }

  
    export namespace ProjectCreatedEvent {
      export type InputTuple = [projectAddress: AddressLike, creator: AddressLike, name: string, fundingGoal: BigNumberish, fundingDeadline: BigNumberish];
      export type OutputTuple = [projectAddress: string, creator: string, name: string, fundingGoal: bigint, fundingDeadline: bigint];
      export interface OutputObject {projectAddress: string, creator: string, name: string, fundingGoal: bigint, fundingDeadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AegisCrowdfundFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): AegisCrowdfundFactory;
    waitForDeployment(): Promise<this>;

    interface: AegisCrowdfundFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createProject: TypedContractMethod<
      [params: AegisCrowdfundFactory.CreateProjectParamsStruct, ],
      [string],
      'nonpayable'
    >
    

    
    creatorProjects: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getProjectCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getProjects: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getProjectsByCreator: TypedContractMethod<
      [_creator: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    governanceToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    projects: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createProject'): TypedContractMethod<
      [params: AegisCrowdfundFactory.CreateProjectParamsStruct, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'creatorProjects'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getProjectCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getProjects'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getProjectsByCreator'): TypedContractMethod<
      [_creator: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'governanceToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'projects'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'ProjectCreated'): TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;

    filters: {
      
      'ProjectCreated(address,address,string,uint256,uint256)': TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
      ProjectCreated: TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
    
    };
  }