/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aegisProjectSol from './AegisProject.sol/index.js';
export type { aegisProjectSol };
export type { AegisCrowdfundFactory } from './AegisCrowdfundFactory.js';
export type { AegisToken } from './AegisToken.js';
export * as factories from './factories/index.js';
export { AegisCrowdfundFactory__factory } from './factories/AegisCrowdfundFactory__factory.js';
export type { AegisProject } from './AegisProject.sol/AegisProject.js';
export { AegisProject__factory } from './factories/AegisProject.sol/AegisProject__factory.js';
export type { IVotesToken } from './AegisProject.sol/IVotesToken.js';
export { IVotesToken__factory } from './factories/AegisProject.sol/IVotesToken__factory.js';
export { AegisToken__factory } from './factories/AegisToken__factory.js';