/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as aegisProjectSol from './AegisProject.sol/index.js';
export { AegisCrowdfundFactory__factory } from './AegisCrowdfundFactory__factory.js';
export { AegisToken__factory } from './AegisToken__factory.js';