/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AegisProject__factory } from './AegisProject__factory.js';
export { IVotesToken__factory } from './IVotesToken__factory.js';