/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IVotesToken, IVotesTokenInterface } from "../../AegisProject.sol/IVotesToken.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "timepoint",
        "type": "uint256"
      }
    ],
    "name": "getPastTotalSupply",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "timepoint",
        "type": "uint256"
      }
    ],
    "name": "getPastVotes",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IVotesToken__factory {
    static readonly abi = _abi;
    static createInterface(): IVotesTokenInterface {
      return new Interface(_abi) as IVotesTokenInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IVotesToken {
      return new Contract(address, _abi, runner) as unknown as IVotesToken;
    }
  }
  